#pragma once

#define STATUS_OK 0
#define STATUS_FAIL 1
#define STATUS_NEW_FRAME 2

#define BITS_IN_BLOCK 32
#define COMMON_OUTPUTS_IN_BLOCK 8
#define SEGMENTS_IN_BLOCK (BITS_IN_BLOCK * COMMON_OUTPUTS_IN_BLOCK)
